version: "3.7"

services:
  db:
      image: postgres
      environment:
        POSTGRES_PASSWORD: "postgres"
      ports:
        - 5433:5432
      volumes:
          - ./postgres-data:/var/lib/postgresql/data
          - ./coreservice.bak:/docker-entrypoint-initdb.d/coreservice.sql
  api:
    build: .
    ports:
      - 8123:5000
    depends_on:
      - db
